### PR TITLE
41 feedback message for save device form

### LINKED ISSUE #41: Feedback notification for send device.
When results return "Ok" then the notification will alert the user that the email should be sent to their inbox, if the results fail it will notify the use that something went wrong.

### PR DESCRIPTION
**Pull request by ConorTighe1995**
I have added feedback messages, email validation with regex and a spinner icon to improve the UI. I have also added the test configs required for react-testing library along with some basic tests for the form.

closes #41

### CODE REVIEW

**Comment by DanielSeehausen** [comment]
@ConorTighe1995 heya conor don't forget to assign the PR to yourself! Other than that it looks perfect

image

File: src/components/Configurator.tsx [hunk 1]
```diff
@@ -526,28 +526,29 @@ class Configurator extends React.Component<any, ConfiguratorState> {
           .on('click', async (selectedBox: SelectedBox) => {
             const isRotatable = selectedBox.module.isRotatable()
             device.unsetSelectModule()
-            device.onContextMenu(d3.event.offsetX, d3.event.offsetY + 20, isRotatable)
+            device.onContextMenu(d3.event.layerX - 30, d3.event.layerY - 30, isRotatable)
```
Comment (DanielSeehausen) [inline src/components/Configurator.tsx]: consider naming the magic constants here

Comment (ConorTighe1995) [reply src/components/Configurator.tsx]: Yep! would be a good call. Ill try fit it in future pr if I can get one in today.
